# Generated by Django 2.2.1 on 2019-08-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_auto_20190808_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
    ]
