# Generated by Django 2.2.1 on 2019-08-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0008_department_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='username',
        ),
    ]
