# Generated by Django 2.0.12 on 2019-08-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0009_auto_20190812_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='email',
        ),
    ]
