# Generated by Django 2.0.12 on 2019-08-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0010_auto_20190815_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('op1', models.CharField(max_length=250)),
                ('op2', models.CharField(max_length=250)),
                ('op3', models.CharField(max_length=250)),
                ('ans', models.CharField(max_length=250)),
            ],
        ),
    ]
