# Generated by Django 2.0.12 on 2019-09-06 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0014_auto_20190904_2216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Python',
            new_name='Advancepython',
        ),
    ]
