# Generated by Django 2.0.12 on 2019-09-06 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0015_auto_20190905_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Android',
            new_name='Advanceandroid',
        ),
    ]
