# Generated by Django 2.0.12 on 2019-10-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0017_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='con_password',
        ),
    ]
